---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    app: nvidia-gpu-device-plugin
rules:
- apiGroups:      ['policy', 'extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  ['privileged']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    app: nvidia-gpu-device-plugin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nvidia-gpu-device-plugin
subjects:
- kind: ServiceAccount
  name: nvidia-gpu-device-plugin
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-gpu-device-plugin
  namespace: kube-system
  labels:
    k8s-app: nvidia-gpu-device-plugin
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: nvidia-gpu-device-plugin
  template:
    metadata:
      labels:
        k8s-app: nvidia-gpu-device-plugin
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccount: nvidia-gpu-device-plugin
      serviceAccountName: nvidia-gpu-device-plugin
      tolerations:
      - key: "node.kubernetes.io/master"
        effect: "NoSchedule"
        operator: "Exists"
      priorityClassName: system-node-critical
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      containers:
      - image: "k8s.gcr.io/nvidia-gpu-device-plugin@sha256:d18b678437fedc4ec4211c20b3e5469a137a44f989da43dc275e4f2678170db4"
        command: ["/usr/bin/nvidia-gpu-device-plugin", "-logtostderr"]
        name: nvidia-gpu-device-plugin
        resources:
          requests:
            cpu: 50m
            memory: 10Mi
        securityContext:
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /device-plugin
        - name: dev
          mountPath: /dev
