apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: nvidia-driver-installer
  namespace: kube-system
  labels:
    app: nvidia-driver-installer
    giantswarm.io/service-type: "managed"
rules:
- apiGroups:      ['policy','extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  ['privileged']
